port: 3000
port_reuse: true
process_count: 1
redis_url: "redis://localhost:6379"
database_url: "mysql://root@localhost:3306/development_settings_test"

session:
  key: "myapp.session"
  store: "encrypted_cookie"
  expires: 10

pipes:
  static:
    headers:
      "Cache-Control": "private, max-age=7200"

secrets:
  description: "Store your test secrets credentials and settings here."
