dist: xenial
sudo: required

services:
  - postgresql
  - redis-server
  - docker

cache:
  directories:
    - bin
    - lib
    - .shards

env:
  - TEST_SUITE=./spec/build_spec_granite.cr
  - TEST_SUITE=./spec/amber

before-install:
  - psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'password';"

script:
  - docker build -t amber-test .
  - docker run --rm amber-test /opt/amber/bin/ameba
  - docker run --rm amber-test crystal tool format --check
  - docker run --rm --network=host amber-test crystal spec $TEST_SUITE

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aaf02221d4649d70b384
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
